repos:
  -   repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
        -   id: black
            args: [--safe, --target-version=py37, --diff]

  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
        -    id: trailing-whitespace
        -    id: end-of-file-fixer
#        -    id: check-yaml # Checks yaml files for parsable syntax
        -    id: check-json # Checks json files for parsable syntax
        -    id: check-added-large-files
        -    id: check-case-conflict # Check for files that would conflict in case-insensitive file systems
        -    id: check-merge-conflict # Check for files that contain merge conflict strings
        -    id: debug-statements # Check for debugger imports and py37+ `breakpoint()` calls in python source.
        -    id: requirements-txt-fixer # Sort entries in requirements.txt

  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.991
      hooks:
        -   id: mypy
            args: [--allow-redefinition, --ignore-missing-imports]

  -   repo: https://github.com/asottile/pyupgrade
      rev: v2.26.0
      hooks:
        -   id: pyupgrade
            args: [--py37-plus]

  -   repo: https://github.com/pycqa/isort/
      rev: 5.10.1
      hooks:
        -   id: isort
            types: [file, python]
#  -   repo: local
#      hooks:
#        -   id: pylint
#            name: pylint
#            entry: pylint
#            language: system
#            types: [python]
#            args:
#              - --rcfile=.pylintrc



  -   repo: https://github.com/asottile/blacken-docs
      rev: v1.12.1
      hooks:
        -   id: blacken-docs
            additional_dependencies: [black~=22.0]
            entry: blacken-docs --skip-errors
